/**
 * Made-in regression table for PR #36 (generated from Tester's probe strings in
 * /tmp/pr36probe: cases*.txt, codes3.txt, strip.mts, plus every Tester string
 * from earlier rounds of this PR and round 4).
 *
 * Expected values are what we want under the current rule, never copied from
 * de6dba0 (de6dba0 read "Made in the USA" as Thailand and "MADE IN MY KITCHEN"
 * as Malaysia).
 *
 * Row: [path, input, country, grade, design]
 * - label: country = confirmed country (grade 'label 95%'), null = 未確認
 * - page / note / parts: country = candidate countries (comma list) with their
 *   grades ('likely' = 較可能 from one page, 'possible', 'mentioned' = 有提及),
 *   null = no candidate
 * - design: 附加資訊 rows ('d:' design, 'b:' brand/HQ), null = none
 */
import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { summarize, type RegPath } from './madeInRegression.testutil';

type Row = [RegPath, string, string | null, string | null, string | null];

const ROWS: Row[] = [
  // ── Tester cases.txt: blockers
  ["label", "設計於德國 中國製造", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國 中國製造", null, null, "d:Germany"],
  ["note", "設計於德國 中國製造", "China", "possible", "d:Germany"],
  ["label", "設計於德國中國製造", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國中國製造", null, null, "d:Germany"],
  ["note", "設計於德國中國製造", "China", "possible", "d:Germany"],
  ["label", "設計於日本 台灣製", "Taiwan", "label 95%", "d:Japan"],
  ["page", "設計於日本 台灣製", null, null, "d:Japan"],
  ["note", "設計於日本 台灣製", "Taiwan", "possible", "d:Japan"],
  ["label", "設計於日本台灣製", "Taiwan", "label 95%", "d:Japan"],
  ["page", "設計於日本台灣製", null, null, "d:Japan"],
  ["note", "設計於日本台灣製", "Taiwan", "possible", "d:Japan"],
  ["label", "研發於德國中國生產", "China", "label 95%", "d:Germany"],
  ["page", "研發於德國中國生產", null, null, "d:Germany"],
  ["note", "研發於德國中國生產", "China", "possible", "d:Germany"],
  ["label", "研發於德國 中國生產", "China", "label 95%", "d:Germany"],
  ["page", "研發於德國 中國生產", null, null, "d:Germany"],
  ["note", "研發於德國 中國生產", "China", "possible", "d:Germany"],
  ["label", "德國設計中國製造", "China", "label 95%", "d:Germany"],
  ["page", "德國設計中國製造", null, null, "d:Germany"],
  ["note", "德國設計中國製造", "China", "possible", "d:Germany"],
  ["label", "Designed in Germany Made in China", "China", "label 95%", "d:Germany"],
  ["page", "Designed in Germany Made in China", "China", "likely", "d:Germany"],
  ["note", "Designed in Germany Made in China", "China", "possible", "d:Germany"],
  // ── Tester cases.txt: new strings
  ["label", "設計於德國　中國製", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國　中國製", null, null, "d:Germany"],
  ["note", "設計於德國　中國製", "China", "possible", "d:Germany"],
  ["label", "設計：德國 產地：中國", "China", "label 95%", "d:Germany"],
  ["page", "設計：德國 產地：中國", "China", "likely", "d:Germany"],
  ["note", "設計：德國 產地：中國", "China", "possible", "d:Germany"],
  ["label", "德國設計 越南製", "Vietnam", "label 95%", "d:Germany"],
  ["page", "德國設計 越南製", null, null, "d:Germany"],
  ["note", "德國設計 越南製", "Vietnam", "possible", "d:Germany"],
  ["label", "設計於德國 越南工廠生產", "Vietnam", "label 95%", "d:Germany"],
  ["page", "設計於德國 越南工廠生產", null, null, "d:Germany"],
  ["note", "設計於德國 越南工廠生產", "Vietnam", "possible", "d:Germany"],
  ["label", "設計於德國製造於中國", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國製造於中國", null, null, "d:Germany"],
  ["note", "設計於德國製造於中國", "China", "possible", "d:Germany"],
  ["label", "德國設計、中國組裝", "China", "label 95%", "d:Germany"],
  ["page", "德國設計、中國組裝", null, null, "d:Germany"],
  ["note", "德國設計、中國組裝", "China", "possible", "d:Germany"],
  ["label", "設計於德國 中国制造", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國 中国制造", null, null, "d:Germany"],
  ["note", "設計於德國 中国制造", "China", "possible", "d:Germany"],
  // ── Tester cases.txt: real German made-in
  ["label", "德國製", "Germany", "label 95%", null],
  ["page", "德國製", null, null, null],
  ["note", "德國製", "Germany", "possible", null],
  ["label", "德國製造", "Germany", "label 95%", null],
  ["page", "德國製造", null, null, null],
  ["note", "德國製造", "Germany", "possible", null],
  ["label", "德國生產", "Germany", "label 95%", null],
  ["page", "德國生產", null, null, null],
  ["note", "德國生產", "Germany", "possible", null],
  ["label", "設計於德國 德國製造", "Germany", "label 95%", null],
  ["page", "設計於德國 德國製造", null, null, "d:Germany"],
  ["note", "設計於德國 德國製造", "Germany", "possible", "d:Germany"],
  ["label", "設計於德國，德國製造", "Germany", "label 95%", null],
  ["page", "設計於德國，德國製造", null, null, "d:Germany"],
  ["note", "設計於德國，德國製造", "Germany", "possible", "d:Germany"],
  ["label", "德國設計 德國製造", "Germany", "label 95%", null],
  ["page", "德國設計 德國製造", null, null, "d:Germany"],
  ["note", "德國設計 德國製造", "Germany", "possible", "d:Germany"],
  // ── Tester cases.txt: not made-in
  // product, not made-in: a note mention only
  ["label", "德國產品", null, null, null],
  ["page", "德國產品", null, null, null],
  ["note", "德國產品", "Germany", "mentioned", null],
  // industry, not made-in: a note mention only
  ["label", "德國產業", null, null, null],
  ["page", "德國產業", null, null, null],
  ["note", "德國產業", "Germany", "mentioned", null],
  ["label", "日本製品", "Japan", "label 95%", null],
  ["page", "日本製品", null, null, null],
  ["note", "日本製品", "Japan", "possible", null],
  ["label", "日本製品 ベビーカー", "Japan", "label 95%", null],
  ["page", "日本製品 ベビーカー", null, null, null],
  ["note", "日本製品 ベビーカー", "Japan", "possible", null],
  // ── Tester cases.txt: HQ
  ["label", "Founded in 1947 in Bayreuth, Germany, made in China", "China", "label 95%", "b:Germany"],
  ["page", "Founded in 1947 in Bayreuth, Germany, made in China", "China", "likely", "b:Germany"],
  ["note", "Founded in 1947 in Bayreuth, Germany, made in China", "China", "possible", "b:Germany"],
  ["label", "Headquartered in Germany; assembled in China", "China", "label 95%", "b:Germany"],
  ["page", "Headquartered in Germany; assembled in China", "China", "likely", "b:Germany"],
  ["note", "Headquartered in Germany; assembled in China", "China", "possible", "b:Germany"],
  ["label", "Based in Germany, manufactured in Germany", "Germany", "label 95%", null],
  ["page", "Based in Germany, manufactured in Germany", "Germany", "likely", "b:Germany"],
  ["note", "Based in Germany, manufactured in Germany", "Germany", "possible", "b:Germany"],
  ["label", "Founded in Germany in 1947, manufactured in China", "China", "label 95%", "b:Germany"],
  ["page", "Founded in Germany in 1947, manufactured in China", "China", "likely", "b:Germany"],
  ["note", "Founded in Germany in 1947, manufactured in China", "China", "possible", "b:Germany"],
  ["label", "Based in Bayreuth, Germany and made in Germany", "Germany", "label 95%", null],
  ["page", "Based in Bayreuth, Germany and made in Germany", "Germany", "likely", "b:Germany"],
  ["note", "Based in Bayreuth, Germany and made in Germany", "Germany", "possible", "b:Germany"],
  ["label", "Headquartered in Germany, with factories in China", null, null, "b:Germany"],
  ["page", "Headquartered in Germany, with factories in China", null, null, "b:Germany"],
  ["note", "Headquartered in Germany, with factories in China", "China", "mentioned", "b:Germany"],
  ["label", "based in Germany, made in Germany", "Germany", "label 95%", null],
  ["page", "based in Germany, made in Germany", "Germany", "likely", "b:Germany"],
  ["note", "based in Germany, made in Germany", "Germany", "possible", "b:Germany"],
  ["label", "成立於德國，中國製造", "China", "label 95%", "b:Germany"],
  ["page", "成立於德國，中國製造", null, null, "b:Germany"],
  ["note", "成立於德國，中國製造", "China", "possible", "b:Germany"],
  ["label", "創立於1947年的德國品牌，產地中國", "China", "label 95%", "b:Germany"],
  ["page", "創立於1947年的德國品牌，產地中國", "China", "likely", "b:Germany"],
  ["note", "創立於1947年的德國品牌，產地中國", "China", "possible", "b:Germany"],
  ["label", "德國廠牌", null, null, "b:Germany"],
  ["page", "德國廠牌", null, null, "b:Germany"],
  ["note", "德國廠牌", null, null, "b:Germany"],
  ["label", "德國廠商", null, null, "b:Germany"],
  ["page", "德國廠商", null, null, "b:Germany"],
  ["note", "德國廠商", null, null, "b:Germany"],
  ["label", "Established in 1947 in Bayreuth, Germany. Made in China", "China", "label 95%", "b:Germany"],
  ["page", "Established in 1947 in Bayreuth, Germany. Made in China", "China", "likely", "b:Germany"],
  ["note", "Established in 1947 in Bayreuth, Germany. Made in China", "China", "possible", "b:Germany"],
  // ── Tester cases.txt: codes
  ["label", "Made in UK", "United Kingdom", "label 95%", null],
  ["page", "Made in UK", "United Kingdom", "likely", null],
  ["note", "Made in UK", "United Kingdom", "possible", null],
  ["label", "Made in U.K.", "United Kingdom", "label 95%", null],
  ["page", "Made in U.K.", "United Kingdom", "likely", null],
  ["note", "Made in U.K.", "United Kingdom", "possible", null],
  ["label", "Made in USA", "United States", "label 95%", null],
  ["page", "Made in USA", "United States", "likely", null],
  ["note", "Made in USA", "United States", "possible", null],
  ["label", "Made in U.S.A.", "United States", "label 95%", null],
  ["page", "Made in U.S.A.", "United States", "likely", null],
  ["note", "Made in U.S.A.", "United States", "possible", null],
  ["label", "Made in PRC", "China", "label 95%", null],
  ["page", "Made in PRC", "China", "likely", null],
  ["note", "Made in PRC", "China", "possible", null],
  ["label", "Made in EU", "European Union", "label 95%", null],
  ["page", "Made in EU", "European Union", "likely", null],
  ["note", "Made in EU", "European Union", "possible", null],
  // IT stays out (Ming)
  ["label", "Made in IT", null, null, null],
  ["page", "Made in IT", null, null, null],
  ["note", "Made in IT", null, null, null],
  // DE stays out (Ming)
  ["label", "Made in DE", null, null, null],
  ["page", "Made in DE", null, null, null],
  ["note", "Made in DE", null, null, null],
  ["label", "made in uk", null, null, null],
  ["page", "made in uk", null, null, null],
  ["note", "made in uk", null, null, null],
  ["label", "UK design team", null, null, null],
  ["page", "UK design team", null, null, null],
  ["note", "UK design team", null, null, null],
  ["label", "Ships from UK", null, null, null],
  ["page", "Ships from UK", null, null, null],
  ["note", "Ships from UK", null, null, null],
  ["label", "Made in the UK", "United Kingdom", "label 95%", null],
  ["page", "Made in the UK", "United Kingdom", "likely", null],
  ["note", "Made in the UK", "United Kingdom", "possible", null],
  ["label", "Made in the USA", "United States", "label 95%", null],
  ["page", "Made in the USA", "United States", "likely", null],
  ["note", "Made in the USA", "United States", "possible", null],
  ["label", "Made in Great Britain", "United Kingdom", "label 95%", null],
  ["page", "Made in Great Britain", "United Kingdom", "likely", null],
  ["note", "Made in Great Britain", "United Kingdom", "possible", null],
  ["label", "Made in United Kingdom", "United Kingdom", "label 95%", null],
  ["page", "Made in United Kingdom", "United Kingdom", "likely", null],
  ["note", "Made in United Kingdom", "United Kingdom", "possible", null],
  ["label", "MADE IN CN", "China", "label 95%", null],
  ["page", "MADE IN CN", "China", "likely", null],
  ["note", "MADE IN CN", "China", "possible", null],
  ["label", "Country of origin: CN", "China", "label 95%", null],
  ["page", "Country of origin: CN", "China", "likely", null],
  ["note", "Country of origin: CN", "China", "possible", null],
  ["label", "MADE IN JP", "Japan", "label 95%", null],
  ["page", "MADE IN JP", "Japan", "likely", null],
  ["note", "MADE IN JP", "Japan", "possible", null],
  ["label", "MADE IN TW", "Taiwan", "label 95%", null],
  ["page", "MADE IN TW", "Taiwan", "likely", null],
  ["note", "MADE IN TW", "Taiwan", "possible", null],
  ["label", "Made in Japan", "Japan", "label 95%", null],
  ["page", "Made in Japan", "Japan", "likely", null],
  ["note", "Made in Japan", "Japan", "possible", null],
  ["label", "Made in Germany", "Germany", "label 95%", null],
  ["page", "Made in Germany", "Germany", "likely", null],
  ["note", "Made in Germany", "Germany", "possible", null],
  ["label", "Made-in omitted: it matched brand/design country without factory/COO evidence.", null, null, null],
  ["page", "Made-in omitted: it matched brand/design country without factory/COO evidence.", null, null, null],
  ["note", "Made-in omitted: it matched brand/design country without factory/COO evidence.", null, null, null],
  ["label", "IT company", null, null, null],
  ["page", "IT company", null, null, null],
  ["note", "IT company", null, null, null],
  ["label", "Cybex is an IT-savvy brand, it ships worldwide", null, null, null],
  ["page", "Cybex is an IT-savvy brand, it ships worldwide", null, null, null],
  ["note", "Cybex is an IT-savvy brand, it ships worldwide", null, null, null],
  // ── Tester cases2.txt
  ["label", "設計於德國 製造於中國", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國 製造於中國", null, null, "d:Germany"],
  ["note", "設計於德國 製造於中國", "China", "possible", "d:Germany"],
  ["label", "設計於德國，製造於中國", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國，製造於中國", null, null, "d:Germany"],
  ["note", "設計於德國，製造於中國", "China", "possible", "d:Germany"],
  ["label", "設計於日本 製造於中國", "China", "label 95%", "d:Japan"],
  ["page", "設計於日本 製造於中國", null, null, "d:Japan"],
  ["note", "設計於日本 製造於中國", "China", "possible", "d:Japan"],
  ["label", "研發於德國 生產於中國", "China", "label 95%", "d:Germany"],
  ["page", "研發於德國 生產於中國", null, null, "d:Germany"],
  ["note", "研發於德國 生產於中國", "China", "possible", "d:Germany"],
  ["label", "德國研發 生產於越南", "Vietnam", "label 95%", "d:Germany"],
  ["page", "德國研發 生產於越南", null, null, "d:Germany"],
  ["note", "德國研發 生產於越南", "Vietnam", "possible", "d:Germany"],
  ["label", "設計於德國 製造：中國", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國 製造：中國", "China", "likely", "d:Germany"],
  ["note", "設計於德國 製造：中國", "China", "possible", "d:Germany"],
  ["label", "德國設計製造", null, null, "d:Germany"],
  ["page", "德國設計製造", null, null, "d:Germany"],
  ["note", "德國設計製造", null, null, "d:Germany"],
  ["label", "設計於德國 生產地：中國", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國 生產地：中國", "China", "likely", "d:Germany"],
  ["note", "設計於德國 生產地：中國", "China", "possible", "d:Germany"],
  ["label", "設計於德國 中國工廠製", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國 中國工廠製", null, null, "d:Germany"],
  ["note", "設計於德國 中國工廠製", "China", "possible", "d:Germany"],
  // "X made" without a hyphen is not read; left as is
  ["label", "Designed in Germany Germany made", null, null, "d:Germany"],
  ["page", "Designed in Germany Germany made", null, null, "d:Germany"],
  ["note", "Designed in Germany Germany made", "Germany", "mentioned", "d:Germany"],
  // "China-made" is not read as made-in; left as is
  ["label", "Designed in Germany, China-made", null, null, "d:Germany"],
  ["page", "Designed in Germany, China-made", null, null, "d:Germany"],
  ["note", "Designed in Germany, China-made", "China", "mentioned", "d:Germany"],
  ["label", "COO: CN", "China", "label 95%", null],
  ["page", "COO: CN", "China", "likely", null],
  ["note", "COO: CN", "China", "possible", null],
  ["label", "Country of Origin: CN", "China", "label 95%", null],
  ["page", "Country of Origin: CN", "China", "likely", null],
  ["note", "Country of Origin: CN", "China", "possible", null],
  ["label", "Made in VN", "Vietnam", "label 95%", null],
  ["page", "Made in VN", "Vietnam", "likely", null],
  ["note", "Made in VN", "Vietnam", "possible", null],
  ["label", "MADE IN P.R.C.", "China", "label 95%", null],
  ["page", "MADE IN P.R.C.", "China", "likely", null],
  ["note", "MADE IN P.R.C.", "China", "possible", null],
  ["label", "Made in Viet Nam", "Vietnam", "label 95%", null],
  ["page", "Made in Viet Nam", "Vietnam", "likely", null],
  ["note", "Made in Viet Nam", "Vietnam", "possible", null],
  ["label", "Made in Vietnam", "Vietnam", "label 95%", null],
  ["page", "Made in Vietnam", "Vietnam", "likely", null],
  ["note", "Made in Vietnam", "Vietnam", "possible", null],
  // ── Tester cases3.txt: blocker 1 family
  ["label", "德國設計 生產於越南", "Vietnam", "label 95%", "d:Germany"],
  ["page", "德國設計 生產於越南", null, null, "d:Germany"],
  ["note", "德國設計 生產於越南", "Vietnam", "possible", "d:Germany"],
  ["label", "德國設計，在中國製造", "China", "label 95%", "d:Germany"],
  ["page", "德國設計，在中國製造", null, null, "d:Germany"],
  ["note", "德國設計，在中國製造", "China", "possible", "d:Germany"],
  ["label", "設計於德國 在中國生產", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國 在中國生產", null, null, "d:Germany"],
  ["note", "設計於德國 在中國生產", "China", "possible", "d:Germany"],
  ["label", "設計於 德國 中國製造", "China", "label 95%", "d:Germany"],
  ["page", "設計於 德國 中國製造", null, null, "d:Germany"],
  ["note", "設計於 德國 中國製造", "China", "possible", "d:Germany"],
  ["label", "設計於德國、日本 中國製造", "China", "label 95%", "d:Germany,d:Japan"],
  ["page", "設計於德國、日本 中國製造", null, null, "d:Germany,d:Japan"],
  ["note", "設計於德國、日本 中國製造", "China", "possible", "d:Germany,d:Japan"],
  ["label", "Designed in Germany, manufactured in China", "China", "label 95%", "d:Germany"],
  ["page", "Designed in Germany, manufactured in China", "China", "likely", "d:Germany"],
  ["note", "Designed in Germany, manufactured in China", "China", "possible", "d:Germany"],
  ["label", "Designed in Germany and produced in Vietnam", "Vietnam", "label 95%", "d:Germany"],
  ["page", "Designed in Germany and produced in Vietnam", null, null, "d:Germany"],
  ["note", "Designed in Germany and produced in Vietnam", "Vietnam", "possible", "d:Germany"],
  // ── Tester cases3.txt: verb/date edge
  ["label", "德國製造於2020年", "Germany", "label 95%", null],
  ["page", "德國製造於2020年", null, null, null],
  ["note", "德國製造於2020年", "Germany", "possible", null],
  ["label", "中國製造於2023年", "China", "label 95%", null],
  ["page", "中國製造於2023年", null, null, null],
  ["note", "中國製造於2023年", "China", "possible", null],
  ["label", "製造於2023", null, null, null],
  ["page", "製造於2023", null, null, null],
  ["note", "製造於2023", null, null, null],
  ["label", "德國製造 於2020年出廠", "Germany", "label 95%", null],
  ["page", "德國製造 於2020年出廠", null, null, null],
  ["note", "德國製造 於2020年出廠", "Germany", "possible", null],
  ["label", "日本製 在庫あり", "Japan", "label 95%", null],
  ["page", "日本製 在庫あり", null, null, null],
  ["note", "日本製 在庫あり", "Japan", "possible", null],
  ["label", "中国製 在庫限り", "China", "label 95%", null],
  ["page", "中国製 在庫限り", null, null, null],
  ["note", "中国製 在庫限り", "China", "possible", null],
  ["label", "日本製在庫あり", "Japan", "label 95%", null],
  ["page", "日本製在庫あり", null, null, null],
  ["note", "日本製在庫あり", "Japan", "possible", null],
  // ── Tester cases3.txt: manufacturer
  ["label", "德國製造商", null, null, "b:Germany"],
  ["page", "德國製造商", null, null, "b:Germany"],
  ["note", "德國製造商", null, null, "b:Germany"],
  ["label", "德國製造商品牌", null, null, "b:Germany"],
  ["page", "德國製造商品牌", null, null, "b:Germany"],
  ["note", "德國製造商品牌", null, null, "b:Germany"],
  ["label", "中國製造商", null, null, "b:China"],
  ["page", "中國製造商", null, null, "b:China"],
  ["note", "中國製造商", null, null, "b:China"],
  ["label", "日本製造商", null, null, "b:Japan"],
  ["page", "日本製造商", null, null, "b:Japan"],
  ["note", "日本製造商", null, null, "b:Japan"],
  ["label", "中國製造商 好孩子", null, null, "b:China"],
  ["page", "中國製造商 好孩子", null, null, "b:China"],
  ["note", "中國製造商 好孩子", null, null, "b:China"],
  ["label", "德國製造商 中國製造", "China", "label 95%", "b:Germany"],
  ["page", "德國製造商 中國製造", null, null, "b:Germany"],
  ["note", "德國製造商 中國製造", "China", "possible", "b:Germany"],
  // ── Tester cases3.txt: no-country design cue eating
  ["label", "設計：人體工學 產地：中國", "China", "label 95%", null],
  ["page", "設計：人體工學 產地：中國", "China", "likely", null],
  ["note", "設計：人體工學 產地：中國", "China", "possible", null],
  ["label", "設計：人體工學 中國製", "China", "label 95%", null],
  ["page", "設計：人體工學 中國製", null, null, null],
  ["note", "設計：人體工學 中國製", "China", "possible", null],
  ["label", "Designed by CYBEX 中國製", "China", "label 95%", null],
  ["page", "Designed by CYBEX 中國製", null, null, null],
  ["note", "Designed by CYBEX 中國製", "China", "possible", null],
  ["label", "Designed by CYBEX 台灣製", "Taiwan", "label 95%", null],
  ["page", "Designed by CYBEX 台灣製", null, null, null],
  ["note", "Designed by CYBEX 台灣製", "Taiwan", "possible", null],
  ["label", "Designed by CYBEX COO: CN", "China", "label 95%", null],
  ["page", "Designed by CYBEX COO: CN", "China", "likely", null],
  ["note", "Designed by CYBEX COO: CN", "China", "possible", null],
  ["label", "Designed by CYBEX MADE IN CN", "China", "label 95%", null],
  ["page", "Designed by CYBEX MADE IN CN", "China", "likely", null],
  ["note", "Designed by CYBEX MADE IN CN", "China", "possible", null],
  ["label", "Designed by CYBEX Country of Origin: CN", "China", "label 95%", null],
  ["page", "Designed by CYBEX Country of Origin: CN", "China", "likely", null],
  ["note", "Designed by CYBEX Country of Origin: CN", "China", "possible", null],
  ["label", "Design: CYBEX 原産国：中国", "China", "label 95%", null],
  ["page", "Design: CYBEX 原産国：中国", "China", "likely", null],
  ["note", "Design: CYBEX 原産国：中国", "China", "possible", null],
  ["label", "Designed by Apple in California 中國組裝", "China", "label 95%", "d:United States"],
  ["page", "Designed by Apple in California 中國組裝", null, null, "d:United States"],
  ["note", "Designed by Apple in California 中國組裝", "China", "possible", "d:United States"],
  // ── Tester cases3.txt: 設計： cues
  ["label", "Design: Germany / COO: CN", "China", "label 95%", "d:Germany"],
  ["page", "Design: Germany / COO: CN", "China", "likely", "d:Germany"],
  ["note", "Design: Germany / COO: CN", "China", "possible", "d:Germany"],
  ["label", "研發：德國", null, null, "d:Germany"],
  ["page", "研發：德國", null, null, "d:Germany"],
  ["note", "研發：德國", null, null, "d:Germany"],
  ["label", "設計地：德國 中國製", "China", "label 95%", "d:Germany"],
  ["page", "設計地：德國 中國製", null, null, "d:Germany"],
  ["note", "設計地：德國 中國製", "China", "possible", "d:Germany"],
  // ── Tester codes3.txt
  ["label", "Made in: CN", "China", "label 95%", null],
  ["page", "Made in: CN", "China", "likely", null],
  ["note", "Made in: CN", "China", "possible", null],
  ["label", "Made in Hong Kong", "Hong Kong", "label 95%", null],
  ["page", "Made in Hong Kong", "Hong Kong", "likely", null],
  ["note", "Made in Hong Kong", "Hong Kong", "possible", null],
  ["label", "Made in HK SAR", "Hong Kong", "label 95%", null],
  ["page", "Made in HK SAR", "Hong Kong", "likely", null],
  ["note", "Made in HK SAR", "Hong Kong", "possible", null],
  // ambiguous: IN right after a cue ending in IN is never India
  ["label", "MADE IN IN", null, null, null],
  ["page", "MADE IN IN", null, null, null],
  ["note", "MADE IN IN", null, null, null],
  ["label", "Origin: ID card", null, null, null],
  ["page", "Origin: ID card", null, null, null],
  ["note", "Origin: ID card", null, null, null],
  ["label", "MADE IN USA", "United States", "label 95%", null],
  ["page", "MADE IN USA", "United States", "likely", null],
  ["note", "MADE IN USA", "United States", "possible", null],
  ["label", "Made in the PRC", "China", "label 95%", null],
  ["page", "Made in the PRC", "China", "likely", null],
  ["note", "Made in the PRC", "China", "possible", null],
  // lower-case codes stay rejected for now (Ming's call)
  ["label", "made in cn", null, null, null],
  ["page", "made in cn", null, null, null],
  ["note", "made in cn", null, null, null],
  ["label", "Brand origin: CN", null, null, null],
  ["page", "Brand origin: CN", null, null, null],
  ["note", "Brand origin: CN", null, null, null],
  ["label", "MADE IN MY KITCHEN", null, null, null],
  ["page", "MADE IN MY KITCHEN", null, null, null],
  ["note", "MADE IN MY KITCHEN", null, null, null],
  ["label", "產地：TW", "Taiwan", "label 95%", null],
  ["page", "產地：TW", "Taiwan", "likely", null],
  ["note", "產地：TW", "Taiwan", "possible", null],
  // DE stays out (Ming)
  ["label", "產地：DE", null, null, null],
  ["page", "產地：DE", null, null, null],
  ["note", "產地：DE", null, null, null],
  ["label", "Origin: CN", "China", "label 95%", null],
  ["page", "Origin: CN", "China", "likely", null],
  ["note", "Origin: CN", "China", "possible", null],
  ["label", "Origin: China", "China", "label 95%", null],
  ["page", "Origin: China", "China", "likely", null],
  ["note", "Origin: China", "China", "possible", null],
  ["label", "Made in MY", "Malaysia", "label 95%", null],
  ["page", "Made in MY", "Malaysia", "likely", null],
  ["note", "Made in MY", "Malaysia", "possible", null],
  ["label", "Made in ID", "Indonesia", "label 95%", null],
  ["page", "Made in ID", "Indonesia", "likely", null],
  ["note", "Made in ID", "Indonesia", "possible", null],
  // ── Tester strip.mts (design / made-in mixes)
  ["label", "Engineered and made in Germany", "Germany", "label 95%", null],
  ["page", "Engineered and made in Germany", "Germany", "likely", null],
  ["note", "Engineered and made in Germany", "Germany", "possible", null],
  ["label", "Designed and manufactured in Germany", "Germany", "label 95%", null],
  ["page", "Designed and manufactured in Germany", "Germany", "likely", null],
  ["note", "Designed and manufactured in Germany", "Germany", "possible", null],
  ["label", "德國設計，中國製造", "China", "label 95%", "d:Germany"],
  ["page", "德國設計，中國製造", null, null, "d:Germany"],
  ["note", "德國設計，中國製造", "China", "possible", "d:Germany"],
  ["label", "German brand, made in Germany", "Germany", "label 95%", null],
  ["page", "German brand, made in Germany", "Germany", "likely", "b:Germany"],
  ["note", "German brand, made in Germany", "Germany", "possible", "b:Germany"],
  ["label", "Made in Germany by a German brand", "Germany", "label 95%", null],
  ["page", "Made in Germany by a German brand", "Germany", "likely", "b:Germany"],
  ["note", "Made in Germany by a German brand", "Germany", "possible", "b:Germany"],
  ["label", "德國品牌\n產地：德國", "Germany", "label 95%", null],
  ["page", "德國品牌\n產地：德國", "Germany", "likely", "b:Germany"],
  ["note", "德國品牌\n產地：德國", "Germany", "possible", "b:Germany"],
  ["label", "德國品牌 產地：德國", "Germany", "label 95%", null],
  ["page", "德國品牌 產地：德國", "Germany", "likely", "b:Germany"],
  ["note", "德國品牌 產地：德國", "Germany", "possible", "b:Germany"],
  ["label", "designed in Japan\n原産国：中国", "China", "label 95%", "d:Japan"],
  ["page", "designed in Japan\n原産国：中国", "China", "likely", "d:Japan"],
  ["note", "designed in Japan\n原産国：中国", "China", "possible", "d:Japan"],
  ["label", "designed in Japan 原産国：中国", "China", "label 95%", "d:Japan"],
  ["page", "designed in Japan 原産国：中国", "China", "likely", "d:Japan"],
  ["note", "designed in Japan 原産国：中国", "China", "possible", "d:Japan"],
  ["label", "ドイツ設計", null, null, "d:Germany"],
  ["page", "ドイツ設計", null, null, "d:Germany"],
  ["note", "ドイツ設計", null, null, "d:Germany"],
  ["label", "設計：ドイツ", null, null, "d:Germany"],
  ["page", "設計：ドイツ", null, null, "d:Germany"],
  ["note", "設計：ドイツ", null, null, "d:Germany"],
  ["label", "製造国：中国", "China", "label 95%", null],
  ["page", "製造国：中国", "China", "likely", null],
  ["note", "製造国：中国", "China", "possible", null],
  ["label", "ドイツ設計 製造国：中国", "China", "label 95%", "d:Germany"],
  ["page", "ドイツ設計 製造国：中国", "China", "likely", "d:Germany"],
  ["note", "ドイツ設計 製造国：中国", "China", "possible", "d:Germany"],
  ["label", "設計：ドイツ 製造国：中国", "China", "label 95%", "d:Germany"],
  ["page", "設計：ドイツ 製造国：中国", "China", "likely", "d:Germany"],
  ["note", "設計：ドイツ 製造国：中国", "China", "possible", "d:Germany"],
  ["label", "Designed in Germany. Made in China.", "China", "label 95%", "d:Germany"],
  ["page", "Designed in Germany. Made in China.", "China", "likely", "d:Germany"],
  ["note", "Designed in Germany. Made in China.", "China", "possible", "d:Germany"],
  ["label", "Designed in Germany and made in China", "China", "label 95%", "d:Germany"],
  ["page", "Designed in Germany and made in China", "China", "likely", "d:Germany"],
  ["note", "Designed in Germany and made in China", "China", "possible", "d:Germany"],
  ["label", "designed in Germany while made in China", "China", "label 95%", "d:Germany"],
  ["page", "designed in Germany while made in China", "China", "likely", "d:Germany"],
  ["note", "designed in Germany while made in China", "China", "possible", "d:Germany"],
  ["label", "Designed in Germany\nMade in China", "China", "label 95%", "d:Germany"],
  ["page", "Designed in Germany\nMade in China", "China", "likely", "d:Germany"],
  ["note", "Designed in Germany\nMade in China", "China", "possible", "d:Germany"],
  ["label", "Cybex, a German brand from Bayreuth", null, null, "b:Germany"],
  ["page", "Cybex, a German brand from Bayreuth", null, null, "b:Germany"],
  ["note", "Cybex, a German brand from Bayreuth", null, null, "b:Germany"],
  ["label", "German-designed", null, null, "d:Germany"],
  ["page", "German-designed", null, null, "d:Germany"],
  ["note", "German-designed", null, null, "d:Germany"],
  ["label", "Bayreuth-based", null, null, null],
  ["page", "Bayreuth-based", null, null, null],
  ["note", "Bayreuth-based", null, null, null],
  ["label", "Germany-engineered", null, null, "d:Germany"],
  ["page", "Germany-engineered", null, null, "d:Germany"],
  ["note", "Germany-engineered", null, null, "d:Germany"],
  ["label", "來自德國的品牌", null, null, "b:Germany"],
  ["page", "來自德國的品牌", null, null, "b:Germany"],
  ["note", "來自德國的品牌", null, null, "b:Germany"],
  ["label", "Assembled in China", "China", "label 95%", null],
  ["page", "Assembled in China", "China", "likely", null],
  ["note", "Assembled in China", "China", "possible", null],
  ["label", "Assembled in Germany from imported parts", "Germany", "label 95%", null],
  ["page", "Assembled in Germany from imported parts", "Germany", "likely", null],
  ["note", "Assembled in Germany from imported parts", "Germany", "possible", null],
  ["label", "研發於德國並於中國生產", "China", "label 95%", "d:Germany"],
  ["page", "研發於德國並於中國生產", null, null, "d:Germany"],
  ["note", "研發於德國並於中國生產", "China", "possible", "d:Germany"],
  ["label", "Designed in Sweden Made in China", "China", "label 95%", "d:Sweden"],
  ["page", "Designed in Sweden Made in China", "China", "likely", "d:Sweden"],
  ["note", "Designed in Sweden Made in China", "China", "possible", "d:Sweden"],
  // German field names are not read; left as is
  ["label", "Developed in Germany Herkunftsland: China", null, null, "d:Germany"],
  ["page", "Developed in Germany Herkunftsland: China", null, null, "d:Germany"],
  ["note", "Developed in Germany Herkunftsland: China", "China", "mentioned", "d:Germany"],
  ["label", "German engineering, Made in China", "China", "label 95%", "d:Germany"],
  ["page", "German engineering, Made in China", "China", "likely", "d:Germany"],
  ["note", "German engineering, Made in China", "China", "possible", "d:Germany"],
  ["label", "Designed by Apple in California. Assembled in China", "China", "label 95%", "d:United States"],
  ["page", "Designed by Apple in California. Assembled in China", "China", "likely", "d:United States"],
  ["note", "Designed by Apple in California. Assembled in China", "China", "possible", "d:United States"],
  ["label", "Manufactured in Germany", "Germany", "label 95%", null],
  ["page", "Manufactured in Germany", "Germany", "likely", null],
  ["note", "Manufactured in Germany", "Germany", "possible", null],
  ["label", "Founded in Germany, produced in Poland", "Poland", "label 95%", "b:Germany"],
  ["page", "Founded in Germany, produced in Poland", null, null, "b:Germany"],
  ["note", "Founded in Germany, produced in Poland", "Poland", "possible", "b:Germany"],
  ["label", "Designed in Germany, country of origin: China", "China", "label 95%", "d:Germany"],
  ["page", "Designed in Germany, country of origin: China", "China", "likely", "d:Germany"],
  ["note", "Designed in Germany, country of origin: China", "China", "possible", "d:Germany"],
  ["label", "Made in Germany. German engineering.", "Germany", "label 95%", null],
  ["page", "Made in Germany. German engineering.", "Germany", "likely", "d:Germany"],
  ["note", "Made in Germany. German engineering.", "Germany", "possible", "d:Germany"],
  // not read (no cue); left as is
  ["label", "German-made", null, null, null],
  ["page", "German-made", null, null, null],
  ["note", "German-made", null, null, null],
  // German wording is not read; left as is
  ["label", "Hergestellt in Deutschland", null, null, null],
  ["page", "Hergestellt in Deutschland", null, null, null],
  ["note", "Hergestellt in Deutschland", null, null, null],
  ["label", "品牌源自德國，產品於中國製造", "China", "label 95%", "b:Germany"],
  ["page", "品牌源自德國，產品於中國製造", null, null, "b:Germany"],
  ["note", "品牌源自德國，產品於中國製造", "China", "possible", "b:Germany"],
  ["label", "德國工藝製造", null, null, "d:Germany"],
  ["page", "德國工藝製造", null, null, "d:Germany"],
  ["note", "德國工藝製造", null, null, "d:Germany"],
  ["label", "原產地：德國（德國設計）", "Germany", "label 95%", null],
  ["page", "原產地：德國（德國設計）", "Germany", "likely", "d:Germany"],
  ["note", "原產地：德國（德國設計）", "Germany", "possible", "d:Germany"],
  // ── Earlier rounds of this PR + round-4 message strings
  ["label", "Made in P.R.C.", "China", "label 95%", null],
  ["page", "Made in P.R.C.", "China", "likely", null],
  ["note", "Made in P.R.C.", "China", "possible", null],
  // ambiguous fail-safe ('goods made in Germany' vs 'German manufacturer'): the 製造商/生產商 rule skips it on purpose
  ["label", "德國製造商品", null, null, "b:Germany"],
  ["page", "德國製造商品", null, null, "b:Germany"],
  ["note", "德國製造商品", null, null, "b:Germany"],
  // ambiguous fail-safe ('goods made in China' vs 'Chinese manufacturer'): the 製造商/生產商 rule skips it on purpose
  ["label", "中國生產商品", null, null, "b:China"],
  ["page", "中國生產商品", null, null, "b:China"],
  ["note", "中國生產商品", null, null, "b:China"],
  ["label", "設計於德國 生產：中國", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國 生產：中國", "China", "likely", "d:Germany"],
  ["note", "設計於德國 生產：中國", "China", "possible", "d:Germany"],
  ["label", "設計於德國 製造地：中國", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國 製造地：中國", "China", "likely", "d:Germany"],
  ["note", "設計於德國 製造地：中國", "China", "possible", "d:Germany"],
  ["label", "德國製造廠商", null, null, "b:Germany"],
  ["page", "德國製造廠商", null, null, "b:Germany"],
  ["note", "德國製造廠商", null, null, "b:Germany"],
  ["label", "Designed by CYBEX Origin: CN", "China", "label 95%", null],
  ["page", "Designed by CYBEX Origin: CN", "China", "likely", null],
  ["note", "Designed by CYBEX Origin: CN", "China", "possible", null],
  ["label", "Designed by CYBEX 原産国：中国", "China", "label 95%", null],
  ["page", "Designed by CYBEX 原産国：中国", "China", "likely", null],
  ["note", "Designed by CYBEX 原産国：中国", "China", "possible", null],
  ["label", "中國製造", "China", "label 95%", null],
  ["page", "中國製造", null, null, null],
  ["note", "中國製造", "China", "possible", null],
  ["label", "製造商", null, null, null],
  ["page", "製造商", null, null, null],
  ["note", "製造商", null, null, null],
  ["label", "生產商", null, null, null],
  ["page", "生產商", null, null, null],
  ["note", "生產商", null, null, null],
  ["label", "製造商品牌", null, null, null],
  ["page", "製造商品牌", null, null, null],
  ["note", "製造商品牌", null, null, null],
  ["label", "製造廠商", null, null, null],
  ["page", "製造廠商", null, null, null],
  ["note", "製造廠商", null, null, null],
  ["label", "中國製造商品牌", null, null, "b:China"],
  ["page", "中國製造商品牌", null, null, "b:China"],
  ["note", "中國製造商品牌", null, null, "b:China"],
  ["label", "MADE IN U.K.", "United Kingdom", "label 95%", null],
  ["page", "MADE IN U.K.", "United Kingdom", "likely", null],
  ["note", "MADE IN U.K.", "United Kingdom", "possible", null],
  ["label", "Manufactured in PRC", "China", "label 95%", null],
  ["page", "Manufactured in PRC", "China", "likely", null],
  ["note", "Manufactured in PRC", "China", "possible", null],
  ["label", "Assembled in UK", "United Kingdom", "label 95%", null],
  ["page", "Assembled in UK", "United Kingdom", "likely", null],
  ["note", "Assembled in UK", "United Kingdom", "possible", null],
  // page reads a capitalised name after Made in; the UK code is not read
  ["label", "Made in Ukraine-style", null, null, null],
  ["page", "Made in Ukraine-style", "Ukraine", "likely", null],
  ["note", "Made in Ukraine-style", null, null, null],
  ["label", "Origin: TH", "Thailand", "label 95%", null],
  ["page", "Origin: TH", "Thailand", "likely", null],
  ["note", "Origin: TH", "Thailand", "possible", null],
  ["label", "原產国：VN", "Vietnam", "label 95%", null],
  ["page", "原產国：VN", "Vietnam", "likely", null],
  ["note", "原產国：VN", "Vietnam", "possible", null],
  ["label", "Assembled in MX", "Mexico", "label 95%", null],
  ["page", "Assembled in MX", "Mexico", "likely", null],
  ["note", "Assembled in MX", "Mexico", "possible", null],
  ["label", "Manufactured in KH", "Cambodia", "label 95%", null],
  ["page", "Manufactured in KH", "Cambodia", "likely", null],
  ["note", "Manufactured in KH", "Cambodia", "possible", null],
  ["label", "Made in BD", "Bangladesh", "label 95%", null],
  ["page", "Made in BD", "Bangladesh", "likely", null],
  ["note", "Made in BD", "Bangladesh", "possible", null],
  ["label", "MADE IN PT", "Portugal", "label 95%", null],
  ["page", "MADE IN PT", "Portugal", "likely", null],
  ["note", "MADE IN PT", "Portugal", "possible", null],
  ["label", "Made in PL", "Poland", "label 95%", null],
  ["page", "Made in PL", "Poland", "likely", null],
  ["note", "Made in PL", "Poland", "possible", null],
  ["label", "Made in CZ", "Czech Republic", "label 95%", null],
  ["page", "Made in CZ", "Czech Republic", "likely", null],
  ["note", "Made in CZ", "Czech Republic", "possible", null],
  ["label", "Made in TR", "Turkey", "label 95%", null],
  ["page", "Made in TR", "Turkey", "likely", null],
  ["note", "Made in TR", "Turkey", "possible", null],
  ["label", "MADE IN MY", "Malaysia", "label 95%", null],
  ["page", "MADE IN MY", "Malaysia", "likely", null],
  ["note", "MADE IN MY", "Malaysia", "possible", null],
  ["label", "MADE IN ID", "Indonesia", "label 95%", null],
  ["page", "MADE IN ID", "Indonesia", "likely", null],
  ["note", "MADE IN ID", "Indonesia", "possible", null],
  ["label", "Made in PH", "Philippines", "label 95%", null],
  ["page", "Made in PH", "Philippines", "likely", null],
  ["note", "Made in PH", "Philippines", "possible", null],
  ["label", "Made in KR", "South Korea", "label 95%", null],
  ["page", "Made in KR", "South Korea", "likely", null],
  ["note", "Made in KR", "South Korea", "possible", null],
  ["label", "Made in HK", "Hong Kong", "label 95%", null],
  ["page", "Made in HK", "Hong Kong", "likely", null],
  ["note", "Made in HK", "Hong Kong", "possible", null],
  ["label", "MADE IN THE USA", "United States", "label 95%", null],
  ["page", "MADE IN THE USA", "United States", "likely", null],
  ["note", "MADE IN THE USA", "United States", "possible", null],
  ["label", "Country of Origin: IN", "India", "label 95%", null],
  ["page", "Country of Origin: IN", "India", "likely", null],
  ["note", "Country of Origin: IN", "India", "possible", null],
  ["label", "COO: IN.", "India", "label 95%", null],
  ["page", "COO: IN.", "India", "likely", null],
  ["note", "COO: IN.", "India", "possible", null],
  ["label", "We ship CN and VN orders fast", null, null, null],
  ["page", "We ship CN and VN orders fast", null, null, null],
  ["note", "We ship CN and VN orders fast", null, null, null],
  ["label", "JP / KR versions differ", null, null, null],
  ["page", "JP / KR versions differ", null, null, null],
  ["note", "JP / KR versions differ", null, null, null],
  ["label", "德國廠牌 Cybex，輕量推車。", null, null, "b:Germany"],
  ["page", "德國廠牌 Cybex，輕量推車。", null, null, "b:Germany"],
  ["note", "德國廠牌 Cybex，輕量推車。", null, null, "b:Germany"],
  ["label", "德國廠商 Cybex 出品。", null, null, "b:Germany"],
  ["page", "德國廠商 Cybex 出品。", null, null, "b:Germany"],
  ["note", "德國廠商 Cybex 出品。", null, null, "b:Germany"],
  ["label", "Cybex 創立於德國。", null, null, "b:Germany"],
  ["page", "Cybex 創立於德國。", null, null, "b:Germany"],
  ["note", "Cybex 創立於德國。", null, null, "b:Germany"],
  ["label", "Cybex 成立於德國，2005 年起推出推車。", null, null, "b:Germany"],
  ["page", "Cybex 成立於德國，2005 年起推出推車。", null, null, "b:Germany"],
  ["note", "Cybex 成立於德國，2005 年起推出推車。", null, null, "b:Germany"],
  ["label", "設計地：德國 產地：中國", "China", "label 95%", "d:Germany"],
  ["page", "設計地：德國 產地：中國", "China", "likely", "d:Germany"],
  ["note", "設計地：德國 產地：中國", "China", "possible", "d:Germany"],
  ["label", "研發：德國 產地：中國", "China", "label 95%", "d:Germany"],
  ["page", "研發：德國 產地：中國", "China", "likely", "d:Germany"],
  ["note", "研發：德國 產地：中國", "China", "possible", "d:Germany"],
  ["label", "Designed: Germany. Made in China", "China", "label 95%", "d:Germany"],
  ["page", "Designed: Germany. Made in China", "China", "likely", "d:Germany"],
  ["note", "Designed: Germany. Made in China", "China", "possible", "d:Germany"],
  ["label", "德國製造於中國", "China", "label 95%", null],
  ["page", "德國製造於中國", null, null, null],
  ["note", "德國製造於中國", "China", "possible", null],
  ["label", "德國生產於越南", "Vietnam", "label 95%", null],
  ["page", "德國生產於越南", null, null, null],
  ["note", "德國生產於越南", "Vietnam", "possible", null],
  ["label", "日本製于中国", "China", "label 95%", null],
  ["page", "日本製于中国", null, null, null],
  ["note", "日本製于中国", "China", "possible", null],
  ["label", "越南工廠生產", "Vietnam", "label 95%", null],
  ["page", "越南工廠生產", null, null, null],
  ["note", "越南工廠生產", "Vietnam", "possible", null],
  ["label", "中國組裝", "China", "label 95%", null],
  ["page", "中國組裝", null, null, null],
  ["note", "中國組裝", "China", "possible", null],
  ["label", "德國產品設計", null, null, null],
  ["page", "德國產品設計", null, null, null],
  ["note", "德國產品設計", "Germany", "mentioned", null],
  ["label", "中國產業", null, null, null],
  ["page", "中國產業", null, null, null],
  ["note", "中國產業", "China", "mentioned", null],
  ["label", "設計於德國，中國產", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國，中國產", null, null, "d:Germany"],
  ["note", "設計於德國，中國產", "China", "possible", "d:Germany"],
  ["label", "Made in the Netherlands", "Netherlands", "label 95%", null],
  ["page", "Made in the Netherlands", "Netherlands", "likely", null],
  ["note", "Made in the Netherlands", "Netherlands", "possible", null],
  ["label", "made in the factory", null, null, null],
  ["page", "made in the factory", null, null, null],
  ["note", "made in the factory", null, null, null],
  ["label", "CYBEX Melio\n設計於德國 中國製造", "China", "label 95%", "d:Germany"],
  ["page", "CYBEX Melio\n設計於德國 中國製造", null, null, "d:Germany"],
  ["note", "CYBEX Melio\n設計於德國 中國製造", "China", "possible", "d:Germany"],
  // same fail-safe as 德國製造商品
  ["label", "設計於德國 中國製造商品", null, null, "d:Germany,b:China"],
  ["page", "設計於德國 中國製造商品", null, null, "d:Germany,b:China"],
  ["note", "設計於德國 中國製造商品", null, null, "d:Germany,b:China"],
  ["label", "設計於德國 中國製", "China", "label 95%", "d:Germany"],
  ["page", "設計於德國 中國製", null, null, "d:Germany"],
  ["note", "設計於德國 中國製", "China", "possible", "d:Germany"],
  ["label", "Engineered in Germany. 輕量 5.9 kg，單手收車。", null, null, "d:Germany"],
  ["page", "Engineered in Germany. 輕量 5.9 kg，單手收車。", null, null, "d:Germany"],
  ["note", "Engineered in Germany. 輕量 5.9 kg，單手收車。", null, null, "d:Germany"],
  ["label", "German engineering for city life.", null, null, "d:Germany"],
  ["page", "German engineering for city life.", null, null, "d:Germany"],
  ["note", "German engineering for city life.", null, null, "d:Germany"],
  ["label", "德國品牌，輕量推車。", null, null, "b:Germany"],
  ["page", "德國品牌，輕量推車。", null, null, "b:Germany"],
  ["note", "德國品牌，輕量推車。", null, null, "b:Germany"],
  ["label", "Cybex is a German brand.", null, null, "b:Germany"],
  ["page", "Cybex is a German brand.", null, null, "b:Germany"],
  ["note", "Cybex is a German brand.", null, null, "b:Germany"],
  // ── componentsOrigin (parts code list): lower case only in a pure code list, only cn tw vn th jp kr hk
  ["parts", "cn / th", "China,Thailand", "possible,possible", null],
  ["parts", "vn, cn", "Vietnam,China", "possible,possible", null],
  ["parts", "jp;kr;hk;tw", "Japan,South Korea,Hong Kong,Taiwan", "possible,possible,possible,possible", null],
  ["parts", "CN / TH / VN", "China,Thailand,Vietnam", "possible,possible,possible", null],
  ["parts", "Often CN / TH / VN (unconfirmed)", "China,Thailand,Vietnam", "possible,possible,possible", null],
  ["parts", "IT parts from CN", "China", "possible", null],
  ["parts", "it is mostly made in china", "China", "possible", null],
  ["parts", "in / id / it / my / ph", null, null, null],
  ["parts", "is / to / no / be / am / me / us", null, null, null],
  ["parts", "frame in cn", null, null, null],
  ["parts", "made in my workshop", null, null, null],
  ["parts", "parts id on the box", null, null, null],
  ["parts", "the ph balance of the fabric", null, null, null],
  ["parts", "motor: cn", null, null, null],
  ["parts", "cn parts and th parts", null, null, null],
];

describe(`made-in regression table (${ROWS.length} rows)`, () => {
  for (const [path, input, country, grade, design] of ROWS) {
    it(`${path} ${JSON.stringify(input)} → ${country ?? '未確認'} ${grade ?? ''} ${design ?? ''}`, () => {
      assert.deepEqual(summarize(path, input), { country, grade, design });
    });
  }
});
